bdn = {
    # Male names
    "Md", "Md.", "Mst", "Abdul", "Akhtar", "Ali", "Amin", "Anis", "Asif", "Aziz", "Bashir", "Bilal", 
    "Faisal", "Farhan", "Habib", "Hassan", "Hossain", "Imran", "Iqbal", "Jamil", "Kamal", "Karim", 
    "Khan", "Mahmud", "Moin", "Monir", "Nasir", "Nawaz", "Rahim", "Rashid", "Rehman", "Salim", 
    "Sami", "Shahid", "Sharif", "Tariq", "Yasin", "Zaman", "Salman", "Wajid", "Sk", "Rahman", 
    "Hasan", "Jahan", "Parvez", "Shakil", "Shahin", "Sohel", "Tarek", "Sajjad", "Raju", "Shamim", 
    "Sumon", "Shahed", "Shakib", "Arif", "Sabbir", "Noman", "Shafi", "Shah", "Shahriar", "Tanvir", 
    "Rafi", "Masud", "Rafiq", "Rakib", "Sobuj", "Shuvo", "Faruk", "Nayeem", "Mehedi", "Munna", 
    "Anwar", "Kabir", "Shuvo", "Rajib", "Sohag", "Sajib", "Rony", "Sakib", "Shahjalal", "Nasim", 
    "Sakil", "Shuvojit", "Sujon", "Ashik", "Shafiq", "Mahfuz", "Habibullah", "Rasel", "Mizan", 
    "Monir", "Mithun", "Mamun", "Shanto", "Mehrab", "Rubel", "Sumon", "Sabbir", "Razib", "Khairul", 
    "Rafat", "Arafat", "Mahbub", "Nizam", "Biplab", "Pavel", "Arman", "Bijoy", "Shanto", "Hasib", 
    "Ranjan", "Masum", "Liton", "Shamim", "Nazim", "Tuhin", "Arman", "Forhad", "Sakif", "Jabed", 
    "Shakir", "Rifat", "Rakib", "Muntasir", "Biplob", "Tuhin", "Rabbi", "Rab", "Sourav", "Jony", 
    "Partha", "Pavel", "Sohan", "Ratul", "Rabiul", "Rifat", "Mizanur", "Jahid", "Alamin", "Tanjim", 
    "Mahir", "Sajal", "Rifat", "Ratul", "Sarwar", "Shihab", "Rajon", "Jamil", "Rasel", "Ahsan", 
    "Maruf", "Tanveer", "Sajjad", "Rifat", "Saiful", "Shohel", "Tuhin", "Anik", "Shuvo", "Ridoy", 
    "Arafat", "Saif", "Hasib", "Bipul", "Jewel", "Sakib", "Sahed", "Sujon", "Mehedi", "Rafat", 
    "Sakib", "Shihab", "Shamim", "Siam", "Munim", "Sharif", "Rana", "Shamim", "Rana", "Kawsar", 
    "Mahmud", "Akash", "Rafi", "Mahbub", "Munna", "Rasel", "Mehedi", "Shohel", "Rakib", "Nayeem", 
    "Rakib", "Mehedi", "Arafat", "Kawsar", "Tahsin", "Rasel", "Arif", "Biplob", "Rakib", "Sajjad", 
    "Tanzim", "Tuhin", "Mehedi", "Mehedi", "Hasan", "Rasel", "Rakib", "Shamim", "Munna", "Rony", 
    "Fahim", "Mehedi", "Jewel", "Rafsan", "Munna", "Shamim", "Najim", "Rakib", "Najim", "Sabbir", 
    "Shanto", "Biplob", "Mithun", "Shamim", "Nazim", "Mukul", "Tahsin", "Anisur", "Abdus", 
    "Mohammad", "Kazi", "Abul", "Nur", "Nazmul", "Sohel", "Monjur", "Arifur", "Mostafizur", 
    "Kamrul", "Sazzad", "Aminul", "Rashed", "Mahfuzur", "Monirul", "Shafiqul", "Imtiaz", "Enamul", 
    "Fakrul", "Mahmudul", "Samsul", "Abdur", "Farid", "Mizanur", "Jahirul", "Helal", "Shahidul", 
    "Liton", "Rezaul", "Jashim", "Selim", "Anwar", "Motiur", "Azizul", "Golam", "Habiba", "Hanif", 
    "Ibrahim", "Jamal", "Kabir", "Harun", "Masud", "Mahim", "Jisan", "Jibon", "Shofik", "Mustakim", 
    "Irfan", "Rahmatullah", "Fazlul", "Shamsul", "Afsar", "Mahbubul", "Shafayat", "Shariful", 
    "Iqra", "Anan", "Ishtiaq", "Ahad", "Ehsanul", "Abdullah", "Shabbir", "Liton", "Masum", 
    "Aklas", "Ashraful", "Atiq", "Mohiuddin", "Najmul", "Feroze", "Jaber", "Ashrafuzzaman", 
    "Mahbubur", "Nazib", "Sadiq", "Shahedul", "Imranul", "Muntashir", "Naushad", "Rashidur", "Touhid", 
    "Wali", "Mahfuzul", "Saad", "Azhar", "Naeem", "Shahiduzzaman", "Tazul", "Helaluddin", "Masudul", 
    "Murshed", "Nure Alam", "Nasrul", "Khalid", "Sayeed", "Maswood", "Shamsuzzaman", "Tanzir", 
    "Nahid", "Shaikh", "Rubayet", "Shadman", "Hasnain", "Shams", "Ibadur", "Arafatul", "Humaun", 
    "Akash", "Tarik", "Shuvo", "Arshad", "Bashar", "Junaid", "Khaled", "Mahin", "Nadir", "Wasim", 
    "Zubair", "Nazrul", "Rashedul", "Zakir", "Aftab", "Anwarul", "Asad", "Fazle", "Khorshed", 
    "Lokman", "Ishraq", "Touhidur", "Hassanuzzaman", "Nusratullah", "Tayef", "Tawfiq", "Zahedul", 
    "Shojib", "Abdulahi", "Shawkat", "Sadat", "Zahidur", "Hossainul", "Adnan", "Tarek", "Saeed",
    
    # Female names
    "Habiba", "Hanif", "Jahanara", "Taslima", "Shapla", "Meher", "Poppy", "Mim", "Arpita", 
    "Shalini", "Alifa", "Afifa", "Afsana", "Tithi", "Sarika", "Tumpa", "Jannat", "Anwara", 
    "Rokeya", "Maliha", "Dilara", "Aziza", "Sanjida", "Mithila", "Nishita", "Tazkia", "Nabila", 
    "Umme", "Rezwana", "Farah", "Samina", "Zerin", "Salma", "Fatema", "Sharmeen", "Fatima", 
    "Suraiya", "Mithu", "Nusrat", "Ayesha", "Mariam", "Afroza", "Sathi", "Rina", "Lovely", 
    "Rima", "Shila", "Sultana", "Mousumi", "Anika", "Nargis", "Nishat", "Pushpa", "Puja", 
    "Ria", "Romana", "Priya", "Shapla", "Tania", "Tohura", "Ananya", "Arifa", "Shirin", 
    "Rumana", "Naima", "Moni", "Farzana", "Tahmina", "Roksana", "Ritu", "Tasnim", "Alpona", 
    "Sabina", "Sima", "Zakia", "Sathi", "Tuli", "Arpita", "Diba", "Nishita", "Samia", 
    "Munia", "Rumki", "Nasrin", "Naima", "Lipi", "Moushumi", "Bithi", "Zannat", "Sumaiya", 
    "Aparna", "Hasina", "Kohinur", "Sabina", "Lamia", "Nasima", "Fariha", "Tasfia", 
    "Sathi", "Naima", "Rekha", "Ashna", "Sanika", "Simran", "Anita", "Supriya", "Tania", 
    "Mitali", "Sujata", "Mahjabeen", "Sabnam", "Mukta", "Dipika", "Suparna", "Shreyashi", 
    "Anwara", "Maliha", "Sultana", "Nazma", "Rozina", "Sheuly", "Lovely", "Liza", "Lima", 
    "Anika", "Jui", "Tania", "Diba", "Roksana", "Tithi", "Tina", "Sonia", "Saba", "Munira", 
    "Mim", "Asha", "Hena", "Suchitra", "Nodi", "Lipi", "Mouri", "Kanta", "Sonali", "Tanisha", 
    "Saima", "Sumona", "Shithi", "Shimu", "Nadia", "Shimu", "Ayesha", "Tamanna", "Ruma", 
    "Sohana", "Mona", "Rehnuma", "Rupa", "Lopa", "Kajol", "Labiba", "Afia", "Nazia", 
    "Swapna", "Sheuly", "Rita", "Mouri", "Farzana", "Mariya", "Tasmin", "Moushumi", "Lota", 
    "Shakila", "Purnima", "Mim", "Tanjina", "Tasfiya", "Eva", "Sushmita", "Arifa", "Doly", 
    "Pushpa", "Nitu", "Sumi", "Shilpi", "Susmita", "Shilpi", "Papiya", "Faria", "Afsari",
    "Begum", "Khatun", "Akter", "Bibi", "Chowdhury", "Sultana", "Rahman", "Hossain", "Ferdous", "Parveen", 
    "Islam", "Rashid", "Karim", "Afroze", "Ahmed", "Mahmud", "Ali", "Hassan", "Salma", "Nahar", 
    "Rumi", "Siddiqui", "Aziz", "Nazneen", "Raisa", "Farhana", "Habib", "Zaman", "Ferdousi", "Tanzila", 
    "Kabir", "Mostafa", "Sanjida", "Jahan", "Rumana", "Jannat", "Afroz", "Hasan", "Sonia", "Sadia", 
    "Raihan", "Tabassum", "Sumi", "Shireen", "Nusrat", "Anika", "Lamia", "Samia", "Rina", "Maliha", 
    "Munira", "Tahmina", "Shahana", "Nabila", "Rezwana", "Zerin", "Kohinur", "Moni", "Arifa", "Farzana", 
    "Sabina", "Anita", "Nasrin", "Sadia", "Tasnim", "Zakia", "Fariha", "Suhana", "Sanam", "Rashida", 
    "Shirin", "Sultana", "Lopa", "Tanjina", "Lima", "Mithila", "Rubina", "Nazma", "Taslima", "Bithi", 
    "Moushumi", "Mim", "Laboni", "Bashira", "Dilara", "Shilpi", "Mouri", "Ayesha", "Humaira", "Shamima", 
    "Afsana", "Nadia", "Purnima", "Ruksana", "Sanjida", "Kajol", "Mukta", "Sheuly", "Jui", "Ayesha", 
    "Shamima", "Mumtaz", "Farida", "Shakila", "Ruma", "Kanta", "Rina", "Nandita", "Rupali", "Kazi", 
    "Hasina", "Parveen", "Shaila", "Afia", "Sabrina", "Fauzia", "Nuzhat", "Rumki", "Tumpa", "Sonali", 
    "Nahar", "Priya", "Dilruba", "Sumaiya", "Naznin", "Shilpy", "Rupa", "Eva", "Sanjida", "Papia", 
    "Razia", "Pinky", "Rukhsana", "Shuchitra", "Sadia", "Dipa", "Maliha", "Hena", "Liza", "Suchitra", 
    "Nishita", "Nandini", "Nabila", "Tuli", "Jesmin", "Monira", "Rozina", "Diba", "Sushmita", "Nafisa", 
    "Puja", "Anwara", "Tasnia", "Hasna", "Ananya", "Nazifa", "Shirin", "Swapna", "Anita", "Sathi", 
    "Sharmeen", "Sufia", "Maria", "Rina", "Mahi", "Sumona", "Nahar", "Arifa", "Tumpa", "Tasnim", 
    "Raisa", "Rubina", "Rezwana", "Tania", "Shapla", "Farhana", "Munira", "Ritu", "Munni", "Sadia", 
    "Fatema", "Sharmin", "Rehana", "Mahbuba", "Mariam", "Lubna", "Mishu", "Masuda", "Afroza", 
    "Kamrun", "Jannatul", "Suraiya", "Tanima", "Shahela", "Arpita", "Shaheda", "Sharmeen", "Nazma", 
    "Nurjahan", "Afia", "Noorjahan", "Tina", "Shaila", "Shumi", "Dipa", "Rosy", "Rani", "Sabina", 
    "Ashrafun", "Shabnam", "Sayeda", "Rekha", "Feroza", "Asma", "Rozina", "Nilufar", "Latifa", 
    "Sabrina", "Mumtaz", "Nahar", "Kanta", "Akhter", "Rozina", "Akther", "Purnima", "Fatima", 
    "Farzana", "Salma", "Shabnam", "Mahi", "Jahanara", "Momi", "Raisa", "Rumi", "Samina", "Sumaya", 
    "Sultana", "Sultana", "Sheuli", "Runa", "Jahan", "Meher", "Neha", "Doly", "Marjan", "Afia", 
    "Nishi", "Jahan", "Nazmin", "Samia", "Sadia", "Labiba", "Fahmida", "Karim", "Akther", "Jui", 
    "Pinky", "Sohana", "Ruksana", "Tahmina", "Asha", "Lubna", "Mehrin", "Shanta", "Afroza", "Shirin", 
    "Lopa", "Afrin", "Shirin", "Farzana", "Sana", "Tamanna", "Sabina", "Papia", "Anamika", "Rumi", 
    "Nahar", "Rifat", "Sheuli", "Anis", "Rabeya", "Sultana", "Parvin", "Shanu", "Rehnuma", "Mukti", 
    "Shirin", "Sarmin", "Naznin", "Lata", "Simla", "Hafsa", "Labiba", "Ratri", "Purnima", "Sweety", 
    "Saba", "Afsana", "Shumi", "Minu", "Shirin", "Shaheda", "Shaila", "Morsheda", "Nazia", "Shirin", 
    "Munira", "Anika", "Fahima", "Mouri", "Shamima", "Suraiya", "Rumi", "Jolly", "Salma", "Nafisa", 
    "Monira", "Ruma", "Nazia", "Rima", "Amina", "Lipi", "Habiba", "Rubina", "Dola", "Shirin", 
    "Zarina", "Sabnam", "Shaila", "Rozina", "Nur", "Shila", "Shireen", "Sabina", "Ayesha", "Rima", 
    "Kohinoor", "Moni", "Sanjida", "Irin", "Runa", "Sumi", "Nira", "Tuli", "Sarina", "Ayesha", 
    "Monira", "Shirin", "Shanta", "Minara", "Rumpa", "Rina", "Naila", "Tania", "Suraiya", "Nodi", 
    "Sanjida", "Sathi", "Jolly", "Shapla", "Alifa", "Tasfiya", "Anwara", "Rosy", "Tania", "Mukti", 
    "Suraiya", "Dilruba", "Shirin", "Aklima", "Shirin", "Nafisa", "Rokeya", "Rekha", "Soma", 
    "Shirin", "Shirin", "Ashrafun", "Taslima", "Sultana", "Reshma", "Dolly", "Farida", "Anowara", 
    "Borna", "Rozina", "Arifa", "Sadia", "Shapla", "Laboni", "Kamrun", "Nandita", "Nazma", 
    "Afroz", "Rubina", "Jesmin", "Hafiza", "Sonia", "Rabeya", "Nargis", "Salma", "Manjura", 
    "Shirin", "Tania", "Marium", "Alpona", "Shuchita", "Swapna", "Selina", "Shirin", "Habiba", 
    "Naznin", "Samira", "Jasmin", "Shapla", "Jerin", "Shamsun", "Jesmin", "Shila", "Meher", 
    "Kamrun", "Shirin", "Nargis", "Sheuly", "Begum", "Borna", "Rojina", "Shirin", "Hasna", 
    "Jesmin", "Ayesha", "Shakila", "Jesmin", "Tuli", "Kamrun", "Rima", "Jesmin", "Soma", 
    "Shamima", "Shabana", "Rezina", "Shila", "Nipa", "Shirin", "Shaila", "Shuchi", "Ruma", 
    "Lopa", "Rozina", "Shimu", "Mursheda", "Sheuli", "Rehana", "Sabina", "Nahar", "Lina", 
    "Rupa", "Ashraf", "Sabnam", "Shirin", "Farhana", "Farzana", "Jesmin", "Rozina", "Munni", 
    "Shathi", "Nandita", "Alina", "Sabina", "Nandini", "Sabnam", "Farzana", "Sanjida", "Fatema", 
    "Mim", "Sheuli", "Shirin", "Sultana", "Parvin", "Nafisa", "Rubina", "Arifa", "Mursheda", 
    "Nazia", "Diba", "Rozina", "Moushumi", "Farida", "Shakila", "Shirin", "Tumpa", "Laboni", 
    "Tania", "Puja", "Naznin", "Sima", "Jolly", "Sumi", "Sonia", "Shirin", "Sultana", "Rozina", 
    "Ruma", "Ferdousi", "Shirin", "Ashrafun", "Fatema", "Shirin", "Tithi", "Faria", "Mursheda", 
    "Hasna", "Afsari", "Runa", "Shirin", "Shirin", "Sheuli", "Rezina", "Shaila", "Nadia", 
    "Jannat", "Shirin", "Rumpa", "Nahar", "Soma", "Tuli", "Anis", "Rezina", "Shirin", "Jolly", 
    "Shila", "Rozina", "Mim", "Soma", "Rafia", "Shirin", "Sadia", "Maliha", "Farzana", 
    "Tania", "Shirin", "Sumi", "Mursheda", "Nipa", "Shirin", "Farida", "Feroza", "Shirin", "Islam",
    "Akhtar", "Akter", "Akhter", "Aktar"
}
